apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-angular-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: angular-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 80
