replicaCount: 2
projectName: angular-app
label: angular-app
containers:
  name: angular-app
  image:
    repository: aakashindia/ui_apps
    tag: v1.0
service:
  type: NodePort
  enabled: true
  port:
    port: 80
    targetPort: 80
    nodePort: 30009